# Executive Summary

<!--
This section provides a condensed view of the entire proposal, one page long.
It should be a comprehensive high-level overview that captures the essence of the proposal, including its goals, methods, expected outcomes, deliverables, and budget.
-->

With funding from the RConsortium, development of the R package `sfnetworks` started over six years ago. The package offers data structures and functions for the tidy analysis of geospatial network data in R. Over the years, `sfnetworks` has proven its relevance as a general-purpose geospatial network analysis tool: it was applied by researchers in multiple scientific domains and is a dependency for more application-specific R packages. However, since the development of `sfnetworks` started, the field of geospatial network analysis has continuously evolved. To keep up with current computational requirements, stay in line with the updates of its dependencies, and remain a relevant tool for both researchers and practitioners, the codebase of `sfnetworks` needs to be updated and extended to a new, stable version: v1.0.

This proposal therefore comprises the release of version 1.0 of `sfnetworks`: a stable tool for the analysis of geospatial networks across various domains that is able to handle geospatial network data of large volume and variety, and can easily be extended for more application-specific purposes. The development is split into four distinct work packages: **1) Update the current codebase** - Refactor existing computation-intensive functions, align existing code with new major releases of dependencies, and address open feature requests and bug reports from the community; **2) Enable high-performance routing** - Implement seamless integration with fast, C++-based routing libraries `dodgr` and `cppRouting`; **3) Enable analysis of out-of-memory network data** - Implement seamless integration with `duckspatial`, an interface to the spatial extension of DuckDB that allows spatial operations to be performed on data outside of R's memory; **4) Document and disseminate** - Update and extend package documentation, publish a journal article and a blogpost, and organize a interactive workshop.

The project is planned to start in November 2026 and have a runtime of 10 months. The first three work packages are allocated an equal amount of time, 10 weeks each, without overlap. The fourth work package is spread over the entire project runtime. The proposal applies for a total funding amount of **10.000 USD**, with an equal amount of **2.500 USD** allocated to each individual work package. The funding is intended to cover labor costs of the main applicant, Lucas van der Meer, for an average of 4h/week over the 10 months project runtime, that he can spend exclusively on the development of `sfnetworks`.

The main deliverable of the project is the release of `sfnetworks v1.0` on CRAN, including extensive documentation, planned for Summer 2027. The development can be tracked on the already existing GitHub repository of `sfnetworks`, that also contains an issue tracker for bug reports and feature requests, a discussion forum, a code of conduct, and detailed contributing guidelines. Three additional deliverables are formulated to disseminate the work to a wide audience and stimulate community engagement: 1) A blogpost on the r-spatial blog presenting the new CRAN release; 2) An academic article published in the Journal of Statistical Software; 3) A cross-language session on geospatial network analysis at the Spatial Data Science Across Languages workshop.

Once completed, the project is meant to benefit the existing, multi-disciplinary user community around `sfnetworks` as well as the broader r-spatial community with interest in network data.
