# Signatories
<!--
This section provides the ISC with a view of the support received from
the community for a proposal. Acceptance isn't predicated on
popularity but community acceptance is important. Willingness to
accept outside input is also a good marker for project delivery.

An optional section would be for R-Core signatories where changes to R
are proposed.
-->

## Project team
<!--
Who are the people responsible for actually delivering the project if
the proposal gets accepted and are already signed up and rearing to
go? Briefly describe all participants and the skills they will bring
to the project.
-->

**Lucas van der Meer** will be the responsible software developer in the project. He is a doctoral researcher at the Department of Geoinformatics of the University of Salzburg, with a focus on spatial network analysis for sustainable transport planning. Lucas is author and maintainer of the `sfnetworks` R package. His supervisor, **Martin Loidl**, will manage the administration and budget.

## Contributors
<!--
Who are the people who have actively helped with this proposal but
won't necessarily be on the core project team later?
-->

- **Robin Lovelace:** Professor of Transport Data Science at the University of Leeds and co-author of the `sfnetworks` package.
- **Andrea Gilardi:** Assistant-Professor of Statistics at the University of Milano-Bicocca and co-author of the `sfnetworks` package.

## Consulted
<!--
Who has been given the opportunity to provide feedback on the
proposal? This should include any R Consortium & ISC members who the
proposal has been discussed with.
-->

- **Edzer Pebesma:** Professor of Geoinformatics at the University of Münster; Ordinary member of the R foundation; Section editor of the Journal of Statistical Software; Organizer of the Spatial Data Science Across Languages workshop; Author of the `sf` package.
- **Inger Fabris-Rotelli:** Professor of Statistics at the University of Pretoria.
- **Rafael Pereira:** Senior researcher and head of data science at the Institute for Applied Economic Research in Brazil; Author of `duckspatial`.
