---
bibliography: references.bib
---

# The Problem

```{=html}
<!--
Outlining the issue / weak point / problem to be solved by this
proposal. This should be a compelling section that sets the reader up
for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Why is it a problem
 - [ ] What will solving the problem enable (why should it be solved)
 - [ ] Brief summary of existing work and previous attempts (e.g., relevant R packages)
 - [ ] If proposing changes to R itself: letter of support from R Core member
-->
```

Geospatial networks are graphs embedded in geographical space. That means that both the nodes and edges in the graph can be represented as geographic features: the nodes most commonly as points, and the edges as linestrings. They play an important role in many different domains, ranging from transportation planning and logistics to ecology and epidemiology. The structure and characteristics of geospatial networks go beyond standard graph topology, and therefore it is crucial to explicitly take space into account when analyzing them.

To facilitate such an integrated workflow, development of the R package `sfnetworks` [@meer2024_2] started over six years ago. This development was co-funded by the RConsortium in the second funding round of 2019, under the project name [Tidy spatial networks in R](https://r-consortium.org/all-projects/2019-group-2.html#tidy-spatial-networks-in-r). The package combines the forces of two popular R packages: `sf`  for spatial data science [@pebesma2018] and `tidygraph` for standard graph analysis [@pedersen2025], with the latter offering a tidy interface to the `igraph` library [@antonov2023]. The core of `sfnetworks` is a dedicated data structure for geospatial networks, that can be provided as input to both the graph analytical functions of `tidygraph` as well as the spatial analytical functions of `sf`, without the need for conversion. Additionally, it contains a set of geospatial network specific functions, such as routines for shortest path calculation, network cleaning and topology modification. `sfnetworks` is designed as a general-purpose package suitable for usage across different application domains, and can be seamlessly integrated in tidyverse workflows.

Over the years, `sfnetworks` has proven its relevance as a general-purpose geospatial network analysis tool, and has been used by researchers in multiple scientific domains. Examples include archaeology [@priss2025; @rodriguez2023], ecology [@bystricky2022; @harrisson2025; @molne2023], economics [@hausler2024], environmental planning [@yan2022], power system planning [@li2023], remote sensing [@roussel2023], spatial statistics [@panzeri2025; @thiede2023], transport planning [@duong2025; @valls2023; @meer2024], and toxicology [@simoncic2022]. Furthermore, `sfnetworks` is a dependency for more application-specific R packages, including `centerline` for extracting centerlines from closed polygons [@tsyplenkov2025], `dci` for the calculation of ecological connectivity in river networks [@arkilanian2026], `geNetIt` for the implementation of spatial graph-theoretic genetic gravity models [@evans2026], `greenR` for the analysis of urban greenness within city networks [@mahajan2024], `rcrisp` for the morphological delineation of riverside urban areas [@forgaci2025], `SeaGraphs` for modeling sea currents as connectivity data [@nagkoulis2025], `tinyVAST` for fitting vector autoregressive spatio-temporal models [@thorson2025], and `tmap.networks` for visualizing spatial network data [@tennekes2026].

However, since the development of `sfnetworks` started, the field of geospatial network analysis has continuously evolved. Geospatial network data have grown immensely in volume and variety, putting larger computational requirements on software tools. New algorithms to handle these data have also been developed. Not for nothing, the network analysis software `igraph` (the main computational backend that `sfnetworks` depends on) has been largely rewritten, refactored and extended. This resulted in the recent release of version 1.0 of the C core and version 2.0 of the R interface, with a focus on stabilization of the API and performance improvement for massive network data. To keep up with current computational requirements, stay in line with the updates of its dependencies, and remain a relevant tool for both researchers and practitioners, the codebase of `sfnetworks` needs to be updated and extended as well to a new, stable version: v1.0.